const globalIgnore = [
  '_id',

  'status_trx',
  'value',
  'key',
  'description',
  'type_trx',
  'type_bon',
  'kadar_customer',

  'is_ct',
  'is_aborted',

  'lokasi_asal',
  'lokasi_tujuan',

  'stock_system',
  'selisih',

  'password',

  'filter_by',
  'filter_value',

  'input_date',
  'aborted_date',
  'edit_date',
  'deleted_date',
  'finished_date',
  'validate_date',
  'kirim_date',
  'selesai_date',
  'serah_date',
  'update_status_date',
  'process_date',
  'closed_date',
  'terima_date',
  'closed_date',

  'jam',
  'tanggal',
  'tanggal_transfer',
  'tanggal_kirim',
  'kode',
  'tanggal_giro',
  'tanggal_input',
  'tanggal_invoice',
  'tanggal_transaksi',
  'tanggal_barang',
  'tanggal_validasi',
  'tanggal_janji',
  'tanggal_faktur',
  'tanggal_janji',
  'tanggal_selesai',
  'tanggal_daftar',

  'tgl_mutasi',
  'jenis_titip',
  'jenis_trx',

  'kode_bank',
  'kode_cabang',
  'ip_address',
  'kode_baki',
  'kode_group',
  'kode_kategori',
  'kode_kategori2',
  'kode_jenis2',
  'kode_kelompok',
  'kode_jenis',
  'kode_barcode',
  'kode_reparasi',
  'kode_barcode_set',
  'kode_customer',
  'kode_customer_1',
  'kode_customer_2',
  'kode_customer_level2',
  'kode_customer_level3',
  'kode_ext',
  'kode_tukar_normal',
  'kode_tukar_set',
  'kode_kas',
  'kode_lokasi',
  'kode_provinsi',
  'kode_kota',
  'kode_kecamatan',
  'kode_supplier',
  'kode_sales',
  'kode_storage',
  'kode_relasi',
  'kode_transaksi',
  'kode_pos',
  'kode_intern',
  'kode_customer_from',
  'kode_customer_to',

  'status_active',
  'status_valid',
  'status_open',
  'status_bayar',
  'status_kirim',
  'status_clos',
  'status_lunas',
  'status_selesai',
  'status_serah',
  'status_aktif',
  'status_intern',
  'status_close',
  'status_terima',
  'status_totalan',

  'total_berat_packing',
  'total_putus_titip',
  'total_pkg',
  'total_denda',
  'total_hutang',
  'total_piutang',
  'total_pembayaran',
  'total_gross',
  'total_ongkos',
  'total_bayar',
  'total_bruto',
  'total_netto',
  'total_netto2',
  'total_netto_ext',
  'total_netto_disc',
  'total_netto_disc_ext',
  'total_rp',
  'total_qty',
  'total_jml_gr',
  'total_jml_rp',
  'total_titip_gr',
  'total_bruto_sistem',
  'total_cash',
  'total_trf',
  'total_giro',
  'total_ciok',
  'total_rongsok',
  'total_titip',
  'total_p',
  'total_k',
  'total_bruto_system',
  'total_bruto_selisih',
  'total_netto_system',
  'total_netto_selisih',
  'total_titip_rp',

  'no_reset',
  'no_giro',
  'no_mutasi',
  'no_bon',
  'no_retur',
  'no_reparasi',
  'no_faktur',
  'no_barang_set',
  'no_barcode',
  'no_outstand',
  'no_titip',
  'no_transaksi',
  'no_timbang',
  'no_ref',
  'no_penjualan',
  'no_pembelian',
  'no_packing',
  'no_ext_packing',
  'no_po',
  'no_preorder',
  'no_totalan',
  'no_terima',
  'no_pindah',
  'no_transfer',
  'no_bayar',
  'no_ext',
  'no_urut',
  'no_tolak',

  'baki',

  'kadar',
  'kadar_cetak',
  'kadar_beli2',
  'kadar_jual2',
  'kadar_modal',
  'kadar_jual',
  'kadar_level2',
  'kadar_level3',
  'kadar_beli',
  'kadar_transaksi',

  'kadar_cetak_asal',
  'kadar_beli_asal',
  'kode_jenis_asal',
  'kadar_cetak_tujuan',
  'kadar_beli_tujuan',
  'kode_jenis_tujuan',

  'bayar_cash',
  'bayar_trf',
  'bayar_giro',
  'bayar_ciok',
  'bayar_rongsok',
  'bayar_titip',

  'harga_beli',
  'harga_emas',
  'harga_jual',
  'harga_aksesoris',

  'awal_titip',
  'awal_qty',
  'awal_rp',
  'awal_bruto',
  'awal_netto',

  'in_titip',
  'in_qty',
  'in_bruto',
  'in_netto',
  'in_rp',

  'out_titip',
  'out_qty',
  'out_bruto',
  'out_netto',
  'out_rp',

  'akhir_titip',
  'akhir_qty',
  'akhir_bruto',
  'akhir_netto',
  'akhir_rp',

  'saldo',
  'saldo_gr',
  'saldo_rp',
  'saldo_rp',
  'saldo_awal',
  'saldo_in',
  'saldo_out',
  'saldo_akhir',

  'sisa_hutang_netto',
  'sisa_hutang_rp',
  'sisa_piutang_netto',
  'sisa_piutang_rp',

  'titip_gr',
  'titip_rp',
  'titip_netto',

  'return_normal',
  'return_rongsok',

  'jumlah_hutang',
  'jumlah_piutang',

  'ongkos_rp',
  'ongkos_reparasi',

  'transfer_rp',
  'transfer_netto',
  'transfer_rp',

  'disc',
  'disc_persen',
  'disc_global',
  'disc_global_persen',

  'qty',
  'qty2',
  'qty_kertas',
  'qty_plastik',

  'plastik',
  'kulit',

  'p',
  'k',
  'pkg',
  'gross',
  'netto',
  'bruto',
  'gross2',
  'netto2',
  'bruto2',

  'pkg_tujuan',
  'pkg_asal',

  'netto_disc',

  'instansi',
  'instansi2',

  'giro_rp',
  'giro_netto',

  'berat_packing',
  'berat_bersih',
  'berat_baki',
  'berat_lain',

  'kategori_transaksi',
  'toleransi_selisih',
  'lebih_pembayaran',
  'level_customer',
  'level_customer_trx',
  'customer_induk',
  'lokasi_gambar',
  'cash_netto',
  'pos_trx',
  'cash_rp',
  'nominal',
  'satuan',
  'diskon',
  'image',
  'curr',

  'send_date',
  'received_date',
  'paid_date',
];

export default globalIgnore;
